services:
  - type: worker
    name: propintels-pdf-worker
    runtime: node
    repo: https://github.com/mertsadekist/propintels
    branch: master
    buildCommand: npm install && npx prisma generate
    startCommand: npm run worker
    plan: free
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        sync: false
      - key: REDIS_URL
        sync: false
      - key: S3_BUCKET
        sync: false
      - key: S3_REGION
        sync: false
      - key: S3_ENDPOINT
        sync: false
      - key: S3_ACCESS_KEY_ID
        sync: false
      - key: S3_SECRET_ACCESS_KEY
        sync: false
      - key: EMAIL_FROM
        sync: false
      - key: EMAIL_API_KEY
        sync: false
      - key: PUPPETEER_EXECUTABLE_PATH
        value: /usr/bin/google-chrome-stable
